const {readCache}=require('./tarkovData');
const calibration=require('../../calibration-config.json');
const transformCache=new WeakMap();
function payload(mode,name){const c=readCache(mode,name);return c?.data?.data||c?.data||{}}
function tr(mode,name,key,fallback){const t=payload(mode,name+'_pt');return t[key]||fallback||key||''}
const svgFiles={customs:'Customs.svg',factory:'Factory.svg','ground-zero':'GroundZero.svg','ground-zero-21':'GroundZero.svg',interchange:'Interchange.svg','the-lab':'Labs.svg',lighthouse:'Lighthouse.svg',reserve:'Reserve.svg',shoreline:'Shoreline.svg','streets-of-tarkov':'StreetsOfTarkov.svg',terminal:'Terminal.svg',woods:'Woods.svg'}; 
const floors={customs:[['Underground_Level','Subsolo'],['Ground_Level','Térreo'],['First_Floor','1º andar'],['Second_Floor','2º andar'],['Third_Floor','3º andar']],factory:[['Basement','Subsolo'],['Ground_Floor','Térreo'],['Second_Floor','2º andar'],['Third_Floor','3º andar']],'ground-zero':[['Underground_Level','Subsolo'],['Ground_Level','Térreo'],['First_Floor','1º andar'],['Second_Floor','2º andar'],['Third_Floor','3º andar']],'ground-zero-21':[['Underground_Level','Subsolo'],['Ground_Level','Térreo'],['First_Floor','1º andar'],['Second_Floor','2º andar'],['Third_Floor','3º andar']],interchange:[['Ground_Level','Exterior'],['First_Floor','1º andar'],['Second_Floor','2º andar']],'the-lab':[['Technical_Level','Nível técnico'],['First_Level','1º nível'],['Second_Level','2º nível']],shoreline:[['Underground_Level','Subsolo'],['Ground_Level','Térreo'],['First_Floor','1º andar'],['Second_Floor','2º andar'],['Third_Floor','3º andar']],'streets-of-tarkov':[['Underground_Level','Subsolo'],['Ground_Level','Térreo'],['First_Floor','1º andar'],['Second_Floor','2º andar'],['Third_Floor','3º andar'],['Fourth_Floor','4º andar'],['Fifth_Floor','5º andar']],terminal:[['Ground_Level','Térreo'],['First_Floor','1º andar']]};
const hiddenMapSlugs=new Set(['factory-night','ground-zero-21','ground-zero-tutorial','the-lab-dark']);
function isDuplicateVariant(m){const s=String(m.normalizedName||'').toLowerCase(),n=String(m.name||'').toLowerCase();return hiddenMapSlugs.has(s)||(s.includes('factory')&&n.includes('night'))||(s.includes('ground-zero')&&(n.includes('21+')||n.includes('tutorial')))||(s.includes('lab')&&n.includes('dark'))}
function maps(mode='regular') {const d=payload(mode,'maps').maps||{};return Object.values(d).filter(m=>!isDuplicateVariant(m)).map(m=>({id:m.id,name:tr(mode,'maps',m.name,m.name),slug:m.normalizedName,svgFile:svgFiles[m.normalizedName]||null,floors:(floors[m.normalizedName]||[]).map(([id,label])=>({id,label})),raidDuration:m.raidDuration,players:m.players,minLevel:m.minPlayerLevel||0,calibration:calibration[m.normalizedName]||null,extracts:(m.extracts||[]).map(x=>({id:x.id,name:x.name,faction:x.faction||'any',position:x.position||null})),bosses:(m.bosses||[]).map((b,i)=>({id:b.id||m.id+'-boss-'+i,name:b.name||b.boss||b.bossName||'Boss',chance:b.spawnChance||0,locations:(b.spawnLocations||[]).map(l=>({name:l.name,chance:l.chance,positions:l.positions||[]}))})),spawns:(m.spawns||[]).filter(s=>s.position).map((s,i)=>({id:m.id+'-spawn-'+i,position:s.position,sides:s.sides||[],zone:s.zoneName||''})),transits:(m.transits||[]).map(x=>({id:x.id,name:x.name||x.transitionName||'Transit',position:x.position||null})),switches:(m.switches||[]).filter(x=>x.position).map((x,i)=>({id:x.id||m.id+'-switch-'+i,name:x.name||x.switchName||'Switch',position:x.position})),lootSummary:{containers:(m.lootContainers||[]).length,loose:(m.lootLoose||[]).length}}))}
function transformFor(cal){let t=transformCache.get(cal);if(!t){const [sx,ox,sy,oy]=cal.transform,rad=(cal.coordinateRotation||0)*Math.PI/180;t={sx,ox,sy,oy,cos:Math.cos(rad),sin:Math.sin(rad)};transformCache.set(cal,t)}return t}
function projectPoint(position,cal){if(!position||!cal?.transform)return null;const {sx,ox,sy,oy,cos,sin}=transformFor(cal),x=position.x,z=position.z,rx=x*cos-z*sin,rz=x*sin+z*cos;return{x:rx*sx+ox,y:rz*(-sy)+oy}}
function overlayPoint(position,cal){if(!position||!cal?.bounds)return null;const p=projectPoint(position,cal),a=projectPoint({x:cal.bounds[0][0],z:cal.bounds[0][1]},cal),b=projectPoint({x:cal.bounds[1][0],z:cal.bounds[1][1]},cal);if(!p||!a||!b)return null;const dx=b.x-a.x,dy=b.y-a.y;if(!dx||!dy)return null;return{u:(p.x-a.x)/dx,v:(p.y-a.y)/dy}}
function pointLayer(position,cal){if(!position||!cal)return null;const y=Number(position.y);if(!Number.isFinite(y))return cal.svgLayer||null;for(const layer of cal.layers||[])for(const extent of layer.extents||[]){const h=extent.height||[];if(y<h[0]||y>=h[1])continue;if(!extent.bounds?.length)return layer.svgLayer||null;for(const b of extent.bounds){const a=b[0],c=b[1],minX=Math.min(a[0],c[0]),maxX=Math.max(a[0],c[0]),minZ=Math.min(a[1],c[1]),maxZ=Math.max(a[1],c[1]);if(position.x>=minX&&position.x<=maxX&&position.z>=minZ&&position.z<=maxZ)return layer.svgLayer||null}}return cal.svgLayer||null}
function decoratePosition(position,cal){if(!position)return null;const overlay=overlayPoint(position,cal);return{...position,projected:projectPoint(position,cal),overlay,overlayInBounds:overlay?overlay.u>=0&&overlay.u<=1&&overlay.v>=0&&overlay.v<=1:null,floor:pointLayer(position,cal)}}
function decorateMap(m){if(!m?.calibration)return m;const cal=m.calibration;return{...m,extracts:m.extracts.map(x=>({...x,position:decoratePosition(x.position,cal)})),spawns:m.spawns.map(x=>({...x,position:decoratePosition(x.position,cal)})),bosses:m.bosses.map(b=>({...b,locations:b.locations.map(l=>({...l,positions:l.positions.map(p=>decoratePosition(p,cal))}))})),transits:m.transits.map(x=>({...x,position:decoratePosition(x.position,cal)})),switches:(m.switches||[]).map(x=>({...x,position:decoratePosition(x.position,cal)}))}}
function mapDetail(mode,idOrName){const m=maps(mode).find(m=>m.id===idOrName||m.name===idOrName||m.slug===idOrName)||null;return decorateMap(m)}
module.exports={maps,mapDetail,projectPoint,overlayPoint,pointLayer,decoratePosition};
