const {readCache}=require('./tarkovData');
const {mapDetail,decoratePosition}=require('./mapEngine');
function payload(mode,name){const c=readCache(mode,name);return c?.data?.data||c?.data||{}}
function dict(mode,name,key){const d=payload(mode,name);return d[key]||d}
function list(mode,name,key){return Object.values(dict(mode,name,key)||{})}
function idx(xs){return new Map(xs.map(x=>[x.id,x]))}
function trans(mode,name){return payload(mode,name+'_pt')||{}}
function tr(map,key,fallback){return (typeof key==='string'&&map[key])||fallback||key||''}
function questCatalog(mode='regular'){
 const tasks=list(mode,'tasks','tasks'),maps=idx(list(mode,'maps','maps')),traders=idx(list(mode,'traders')),items=idx(list(mode,'items','items'));const tt=trans(mode,'tasks'),mt=trans(mode,'maps'),rt=trans(mode,'traders'),it=trans(mode,'items');
 return tasks.map(t=>{const m=maps.get(t.map),r=traders.get(t.trader);const mapName=m?tr(mt,m.name,m.name):'Any';const traderName=r?tr(rt,r.name,r.name):t.trader;
 return{id:t.id,name:tr(tt,t.name,t.normalizedName||t.name),normalizedName:t.normalizedName||'',level:t.minPlayerLevel||1,trader:traderName,map:mapName,mapId:t.map||null,kappaRequired:!!t.kappaRequired,storyline:Boolean(t.storyline||t.isStoryline||t.taskType==='Story'||t.type==='Story'||(t.categories||[]).some(category=>String(category).toLowerCase()==='story')),
 objectives:(t.objectives||[]).map(o=>({id:o.id,type:o.type,description:tr(tt,o.description,o.description),count:o.count||1,foundInRaid:!!o.foundInRaid,optional:!!o.optional,items:(o.items||[]).map(id=>{const x=items.get(id);return{id,name:x?tr(it,x.name,x.name):id,icon:x?.iconLink||x?.image512pxLink||''}}),maps:(o.maps||[]).map(id=>{const x=maps.get(id);return x?tr(mt,x.name,x.name):id}),mapIds:o.maps||[],zones:(o.zones||[]).filter(z=>z.position).map(z=>({mapId:z.map,position:z.position,outline:z.outline||[],y:z.position?.y??null})),possibleLocations:(o.possibleLocations||[]).map(x=>({mapId:x.map,positions:x.positions||[]}))})),
 requirements:(t.taskRequirements||[]).map(x=>({taskId:x.task,status:x.status||[]})),neededKeys:t.neededKeys||[],rewards:rewardSummary(t.finishRewards||{},items,it,rt,traders),wikiLink:t.wikiLink||'',image:t.taskImageLink||''}})}
function rewardSummary(reward,items,it,rt,traders){const entries=[],xp=Number(reward.experience||reward.exp||0),money=Number(reward.money||reward.rubles||0),pretty=value=>String(value||'Comerciante').replace(/\b\w/g,letter=>letter.toUpperCase());if(xp)entries.push({kind:'xp',label:xp.toLocaleString('pt-BR')+' EXP'});if(money)entries.push({kind:'money',label:money.toLocaleString('pt-BR')+' ₽'});for(const row of reward.items||[]){const id=row.item||row.id||row.itemId,x=items.get(id),count=Number(row.count||row.quantity||1),itemName=x?tr(it,x.name,x.name):'';if(/rouble|ruble|rublo|рубл/i.test(itemName)){entries.push({kind:'money',label:count.toLocaleString('pt-BR')+' ₽',icon:x?.iconLink||x?.image512pxLink||''});continue}entries.push({kind:'item',label:(itemName||'Item de recompensa')+(count>1?' ×'+count:''),icon:x?.iconLink||x?.image512pxLink||''})}for(const row of reward.traderStanding||reward.traderReputation||[]){const trader=row.trader||row.traderId,amount=Number(row.standing??row.reputation??row.amount??0),traderData=traders?.get(trader);let traderName=traderData?tr(rt,traderData.name,traderData.normalizedName||'Comerciante'):(rt[trader]||'Comerciante');if(/^[0-9a-f]{12,}/i.test(traderName))traderName=traderData?.normalizedName||'Comerciante';entries.push({kind:'rep',label:pretty(traderName)+' '+(amount>=0?'+':'')+amount.toFixed(2)})}return entries}
function questSummary(mode='regular'){const q=questCatalog(mode),maps={};for(const x of q)maps[x.map]=(maps[x.map]||0)+1;return{count:q.length,byMap:Object.entries(maps).sort((a,b)=>b[1]-a[1]),quests:q}}
function kappaTracker(mode='regular',progress=[]){const state=new Map(progress.map(x=>[x.id,x.status])),catalog=questCatalog(mode),quests=catalog.filter(q=>q.kappaRequired).map(q=>({...q,status:state.get(q.id)||'pending'})),collector=catalog.find(q=>/\bthe collector\b|\bcollector\b/i.test(q.normalizedName||q.name)),collectorItems=[...new Map((collector?.objectives||[]).flatMap(objective=>objective.items||[]).map(item=>[item.id,item])).values()];return{total:quests.length,completed:quests.filter(q=>q.status==='completed').length,quests,collector:collector?{id:collector.id,name:collector.name,items:collectorItems}:null}}
function questLines(mode='regular',progress=[]){
 const catalog=questCatalog(mode),byId=new Map(catalog.map(quest=>[quest.id,quest])),status=new Map(progress.map(row=>[row.id,row.status]));
 const definitions=[
  {id:'icebreaker',name:'Icebreaker',summary:'Acesso e missões da expedição Icebreaker.',lore:'Boreas é o quebra-gelo da Paradigm Shipping preso no bloqueio de Tarkov. A linha reúne a expedição e os marcos de acesso registrados na base local.',source:'https://escapefromtarkov.fandom.com/wiki/Icebreaker',matches:quest=>quest.trader==='Icebreaker'||quest.map==='Icebreaker'||/^(persista nisso|ressaca)$/i.test(quest.name)},
  {id:'labyrinth',name:'O Labirinto',summary:'Acesso, etapas e consequências da linha do Labirinto.',lore:'A campanha investiga a instalação subterrânea associada à Knossos LLC sob o Health Resort e o que aconteceu com a equipe BEAR.',source:'https://escapefromtarkov.fandom.com/wiki/The_Labyrinth_(story_chapter)',matches:quest=>/labirinto|labyrinth/i.test(quest.trader+' '+quest.map)},
  {id:'lightkeeper',name:'Lightkeeper',summary:'Caminho completo de desbloqueio e tarefas do Lightkeeper.',lore:'O acesso seguro ao farol depende do transmissor DSP codificado. A cadeia começa em Provedor de Rede - Parte 1 e então reúne as tarefas oferecidas pelo Lightkeeper.',source:'https://escapefromtarkov.fandom.com/wiki/Network_Provider_-_Part_1',matches:quest=>/lightkeeper/i.test(quest.trader)||/^provedor de rede/i.test(quest.name)},
  {id:'gunsmith',name:'Gunsmith',summary:'Todas as montagens pedidas pelo Mechanic.',lore:'O Mechanic pede armas configuradas para clientes e testes; cada etapa define uma plataforma e requisitos técnicos próprios.',source:'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_1',matches:quest=>/^(gunsmith|armeiro)/i.test(quest.name)},
  {id:'chemical',name:'Chemical',summary:'Investigação química e suas escolhas de entrega.',lore:'Skier inicia uma investigação sobre o antigo chefe de segurança da Polikhim. As entregas posteriores podem mudar a rota entre comerciantes.',source:'https://escapefromtarkov.fandom.com/wiki/Chemical_-_Part_1',matches:quest=>/^(chemical|química)/i.test(quest.name)}
 ];
 const lineage=seeds=>{const selected=new Set(seeds.map(quest=>quest.id)),visiting=new Set(),ordered=[];const visit=id=>{if(visiting.has(id)||ordered.some(quest=>quest.id===id))return;const quest=byId.get(id);if(!quest)return;visiting.add(id);quest.requirements.forEach(requirement=>visit(requirement.taskId));visiting.delete(id);ordered.push({...quest,lineRole:selected.has(id)?'line':'prerequisite',status:status.get(id)||'pending'})};seeds.forEach(quest=>visit(quest.id));return ordered};
 const featuredIds=new Set(definitions.flatMap(definition=>catalog.filter(definition.matches).map(quest=>quest.id)));
 const series=new Map();catalog.filter(quest=>!featuredIds.has(quest.id)).forEach(quest=>{const name=quest.name.replace(/\s*[-–]\s*(parte|part)\s*\d+.*$/i,'').trim();if(name!==quest.name.trim()&&name.length>2){const group=series.get(name)||[];group.push(quest);series.set(name,group)}});
 const generated=[...series.entries()].filter(([,quests])=>quests.length>1).map(([name,quests])=>({id:'series-'+name.toLowerCase().replace(/[^a-z0-9]+/gi,'-'),name,summary:'Sequência de quests com etapas encadeadas.',lore:'Contexto narrativo pendente de revisão editorial. Os requisitos e a ordem abaixo vêm do catálogo local.',matches:quest=>quests.some(entry=>entry.id===quest.id),generated:true}));
 return [...definitions,...generated].map(definition=>{const quests=lineage(catalog.filter(definition.matches)),lineQuests=quests.filter(quest=>quest.lineRole==='line'),completed=lineQuests.filter(quest=>quest.status==='completed').length;return{...definition,quests,total:lineQuests.length,completed,requirements:quests.length-lineQuests.length}}).filter(line=>line.total);
}
function reqSatisfied(r,status){const current=status.get(r.taskId);const wanted=r.status||[];if(!wanted.length)return current==='completed';return wanted.some(s=>(s==='complete'&&current==='completed')||(s==='active'&&current==='active')||(s==='failed'&&current==='failed')||s===current)}
function planQuests(mode='regular',progress=[],playerLevel=1){const qs=questCatalog(mode),status=new Map(progress.map(x=>[x.id,x.status]));const byId=new Map(qs.map(q=>[q.id,q]));return qs.map(q=>{let s=status.get(q.id);if(!s){const levelOk=playerLevel>=q.level;const reqOk=q.requirements.every(r=>reqSatisfied(r,status));s=levelOk&&reqOk?'available':'locked'}return{...q,status:s,blockedBy:q.requirements.filter(r=>!reqSatisfied(r,status)).map(r=>byId.get(r.taskId)?.name||r.taskId)}})}
function raidPlan(mode='regular',mapName,progress=[],playerLevel=1,focusQuestId=''){const map=mapName?mapDetail(mode,mapName):null,cal=map?.calibration||null,items=idx(list(mode,'items','items')),it=trans(mode,'items');const qs=planQuests(mode,progress,playerLevel).filter(q=>(focusQuestId?q.id===focusQuestId:['active','available'].includes(q.status))&&(!mapName||q.map===mapName||q.objectives.some(o=>o.maps.includes(mapName)))).map(q=>({...q,objectives:q.objectives.map(o=>({...o,zones:o.zones.map(z=>z.mapId===map?.id?{...z,position:decoratePosition(z.position,cal)}:z),possibleLocations:o.possibleLocations.map(l=>l.mapId===map?.id?{...l,positions:l.positions.map(p=>decoratePosition(p,cal))}:l)}))}));const keys=new Map(),objectiveItems=new Map();for(const q of qs){for(const requirement of q.neededKeys||[]){if(map&&requirement.map!==map.id)continue;for(const id of requirement.keys||[]){const item=items.get(id),current=keys.get(id)||{id,name:item?tr(it,item.name,item.name):id,icon:item?.iconLink||item?.image512pxLink||'',quests:[]};if(!current.quests.includes(q.name))current.quests.push(q.name);keys.set(id,current)}}for(const o of q.objectives){if(map&&q.map!==mapName&&!o.maps.includes(mapName))continue;for(const item of o.items||[]){const current=objectiveItems.get(item.id)||{...item,quests:[],foundInRaid:false};if(!current.quests.includes(q.name))current.quests.push(q.name);current.foundInRaid=current.foundInRaid||o.foundInRaid;objectiveItems.set(item.id,current)}}}return{map:mapName||'Todos',quests:qs,objectiveCount:qs.reduce((n,q)=>n+q.objectives.length,0),keys:[...keys.values()],objectiveItems:[...objectiveItems.values()]}}
module.exports={questCatalog,questSummary,planQuests,raidPlan,kappaTracker,questLines};
