const {readCache}=require('./tarkovData');
const {mapDetail,decoratePosition}=require('./mapEngine');
function payload(mode,name){const c=readCache(mode,name);return c?.data?.data||c?.data||{}}
function dict(mode,name,key){const d=payload(mode,name);return d[key]||d}
function list(mode,name,key){return Object.values(dict(mode,name,key)||{})}
function idx(xs){return new Map(xs.map(x=>[x.id,x]))}
function trans(mode,name){return payload(mode,name+'_pt')||{}}
function tr(map,key,fallback){return (typeof key==='string'&&map[key])||fallback||key||''}
function questCatalog(mode='regular'){
 const tasks=list(mode,'tasks','tasks'),maps=idx(list(mode,'maps','maps')),traders=idx(list(mode,'traders')),items=idx(list(mode,'items','items'));const tt=trans(mode,'tasks'),mt=trans(mode,'maps'),rt=trans(mode,'traders'),it=trans(mode,'items');
 return tasks.map(t=>{const m=maps.get(t.map),r=traders.get(t.trader);const mapName=m?tr(mt,m.name,m.name):'Any';const traderName=r?tr(rt,r.name,r.name):t.trader;
 return{id:t.id,name:tr(tt,t.name,t.normalizedName||t.name),normalizedName:t.normalizedName||'',level:t.minPlayerLevel||1,trader:traderName,map:mapName,mapId:t.map||null,kappaRequired:!!t.kappaRequired,storyline:Boolean(t.storyline||t.isStoryline||t.taskType==='Story'||t.type==='Story'||(t.categories||[]).some(category=>String(category).toLowerCase()==='story')),
 objectives:(t.objectives||[]).map(o=>({id:o.id,type:o.type,description:tr(tt,o.description,o.description),count:o.count||1,foundInRaid:!!o.foundInRaid,optional:!!o.optional,items:(o.items||[]).map(id=>{const x=items.get(id);return{id,name:x?tr(it,x.name,x.name):id,icon:x?.iconLink||x?.image512pxLink||''}}),maps:(o.maps||[]).map(id=>{const x=maps.get(id);return x?tr(mt,x.name,x.name):id}),mapIds:o.maps||[],zones:(o.zones||[]).filter(z=>z.position).map(z=>({mapId:z.map,position:z.position,outline:z.outline||[],y:z.position?.y??null})),possibleLocations:(o.possibleLocations||[]).map(x=>({mapId:x.map,positions:x.positions||[]}))})),
 requirements:(t.taskRequirements||[]).map(x=>({taskId:x.task,status:x.status||[]})),neededKeys:t.neededKeys||[],rewards:rewardSummary(t.finishRewards||{},items,it,rt),wikiLink:t.wikiLink||'',image:t.taskImageLink||''}})}
function rewardSummary(reward,items,it,rt){const entries=[],xp=Number(reward.experience||reward.exp||0),money=Number(reward.money||reward.rubles||0);if(xp)entries.push({kind:'xp',label:xp.toLocaleString('pt-BR')+' EXP'});if(money)entries.push({kind:'money',label:money.toLocaleString('pt-BR')+' ₽'});for(const row of reward.items||[]){const id=row.item||row.id||row.itemId,x=items.get(id),count=Number(row.count||row.quantity||1);entries.push({kind:'item',label:(x?tr(it,x.name,x.name):id)+(count>1?' ×'+count:''),icon:x?.iconLink||x?.image512pxLink||''})}for(const row of reward.traderStanding||reward.traderReputation||[]){const trader=row.trader||row.traderId,amount=Number(row.standing??row.reputation??row.amount??0);entries.push({kind:'rep',label:(rt[trader]||trader||'Trader')+' '+(amount>=0?'+':'')+amount.toFixed(2)})}return entries}
function questSummary(mode='regular'){const q=questCatalog(mode),maps={};for(const x of q)maps[x.map]=(maps[x.map]||0)+1;return{count:q.length,byMap:Object.entries(maps).sort((a,b)=>b[1]-a[1]),quests:q}}
function kappaTracker(mode='regular',progress=[]){const state=new Map(progress.map(x=>[x.id,x.status]));const quests=questCatalog(mode).filter(q=>q.kappaRequired).map(q=>({...q,status:state.get(q.id)||'pending'}));return{total:quests.length,completed:quests.filter(q=>q.status==='completed').length,quests}}
function reqSatisfied(r,status){const current=status.get(r.taskId);const wanted=r.status||[];if(!wanted.length)return current==='completed';return wanted.some(s=>(s==='complete'&&current==='completed')||(s==='active'&&current==='active')||(s==='failed'&&current==='failed')||s===current)}
function planQuests(mode='regular',progress=[],playerLevel=1){const qs=questCatalog(mode),status=new Map(progress.map(x=>[x.id,x.status]));const byId=new Map(qs.map(q=>[q.id,q]));return qs.map(q=>{let s=status.get(q.id);if(!s){const levelOk=playerLevel>=q.level;const reqOk=q.requirements.every(r=>reqSatisfied(r,status));s=levelOk&&reqOk?'available':'locked'}return{...q,status:s,blockedBy:q.requirements.filter(r=>!reqSatisfied(r,status)).map(r=>byId.get(r.taskId)?.name||r.taskId)}})}
function raidPlan(mode='regular',mapName,progress=[],playerLevel=1,focusQuestId=''){const map=mapName?mapDetail(mode,mapName):null,cal=map?.calibration||null,items=idx(list(mode,'items','items')),it=trans(mode,'items');const qs=planQuests(mode,progress,playerLevel).filter(q=>(['active','available'].includes(q.status)||q.id===focusQuestId)&&(!mapName||q.map===mapName||q.objectives.some(o=>o.maps.includes(mapName)))).map(q=>({...q,objectives:q.objectives.map(o=>({...o,zones:o.zones.map(z=>z.mapId===map?.id?{...z,position:decoratePosition(z.position,cal)}:z),possibleLocations:o.possibleLocations.map(l=>l.mapId===map?.id?{...l,positions:l.positions.map(p=>decoratePosition(p,cal))}:l)}))}));const keys=new Map(),objectiveItems=new Map();for(const q of qs){for(const requirement of q.neededKeys||[]){if(map&&requirement.map!==map.id)continue;for(const id of requirement.keys||[]){const item=items.get(id),current=keys.get(id)||{id,name:item?tr(it,item.name,item.name):id,icon:item?.iconLink||item?.image512pxLink||'',quests:[]};if(!current.quests.includes(q.name))current.quests.push(q.name);keys.set(id,current)}}for(const o of q.objectives){if(map&&q.map!==mapName&&!o.maps.includes(mapName))continue;for(const item of o.items||[]){const current=objectiveItems.get(item.id)||{...item,quests:[],foundInRaid:false};if(!current.quests.includes(q.name))current.quests.push(q.name);current.foundInRaid=current.foundInRaid||o.foundInRaid;objectiveItems.set(item.id,current)}}}return{map:mapName||'Todos',quests:qs,objectiveCount:qs.reduce((n,q)=>n+q.objectives.length,0),keys:[...keys.values()],objectiveItems:[...objectiveItems.values()]}}
module.exports={questCatalog,questSummary,planQuests,raidPlan,kappaTracker};
