const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const fs = require('fs');
const path = require('path');
const { initDb,getDashboard,commandOverview,savedBuilds,saveBuild,shoppingList,addShoppingItem,completeShoppingItem,addBuildMissingToShopping,raidHistory,addRaidLog,goalsList,addGoal,completeGoal,mapPins,addMapPin,removeMapPin,favorites,toggleFavorite,stashItems,setStashItem,addReminder,completeReminder,toggleQuest,saveSetting,getSetting,playerLevel,questProgress,setQuestStatus,toggleObjective,objectiveProgress,raidKits,saveRaidKit,removeRaidKit,exportProfile,importProfile } = require('./services/db');
const { syncCore, getStatus } = require('./services/tarkovData');
const { getBattlePassDocuments } = require('./services/battlePass');
const { questSummary, planQuests, raidPlan, kappaTracker } = require('./services/questEngine');
const { maps, mapDetail, projectPoint, pointLayer } = require('./services/mapEngine');
const { tarkovPair } = require('./services/gameClock');
const { catalog:armoryCatalog,details:armoryDetails } = require('./services/armory');
const { catalog:hideoutCatalog } = require('./services/hideout');
const { catalog:marketCatalog } = require('./services/market');
const { setDataRoot } = require('./shared/dataStorage');
let win; const svgCache=new Map();
function createWindow() {
  win = new BrowserWindow({ title: 'Tarkas', width: 1440, height: 900, minWidth: 1050, minHeight: 700,
    backgroundColor: '#0b0d0c', show: false,
    webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false } });
  win.loadFile(path.join(__dirname, 'renderer', 'index.html'));
  ipcMain.removeHandler('map:svg'); ipcMain.handle('map:svg',(_e,file)=>{if(!/^[A-Za-z0-9.-]+\.svg$/.test(file||''))return null;if(svgCache.has(file))return svgCache.get(file);try{let s=require('fs').readFileSync(path.join(__dirname,'..','assets','maps',file),'utf8');s=s.replace(/<\?xml[^>]*>|<!--[^]*?-->/g,'').replace(/>\s+</g,'><').trim();svgCache.set(file,s);return s}catch{return null}});
  win.once('ready-to-show', () => win.show());
}
app.commandLine.appendSwitch('disable-gpu-shader-disk-cache');
app.commandLine.appendSwitch('disable-gpu-program-cache');
app.commandLine.appendSwitch('disk-cache-size','1');
app.commandLine.appendSwitch('disable-features','DawnGraphiteCache');
const gotLock=app.requestSingleInstanceLock();
if(!gotLock){app.quit()}else{
app.on('second-instance',()=>{if(win){if(win.isMinimized())win.restore();win.show();win.focus()}});
app.whenReady().then(async()=>{setDataRoot(path.join(app.getPath('userData'),'game-data'));initDb();const last=getStatus().last;if(!last){await syncCore('regular').catch(()=>{})}createWindow();const age=last?.updatedAt?Date.now()-Date.parse(last.updatedAt):0;if(last&&age>6*60*60*1000)setTimeout(()=>syncCore('regular').catch(()=>{}),2500);});
}
app.on('window-all-closed',()=>app.quit());
ipcMain.handle('dashboard:get',()=>getDashboard());
ipcMain.handle('command:overview',()=>commandOverview());
ipcMain.handle('kits:list',()=>raidKits()); ipcMain.handle('kits:save',(_e,name,items)=>saveRaidKit(name,items)); ipcMain.handle('kits:remove',(_e,id)=>removeRaidKit(id));
ipcMain.handle('profile:export',async()=>{const choice=await dialog.showSaveDialog(win,{title:'Salvar backup do Tarkas',defaultPath:'tarkas-backup.json',filters:[{name:'Backup do Tarkas',extensions:['json']} ]});if(choice.canceled||!choice.filePath)return null;fs.writeFileSync(choice.filePath,JSON.stringify(exportProfile(),null,2),'utf8');return choice.filePath});
ipcMain.handle('profile:import',async()=>{const choice=await dialog.showOpenDialog(win,{title:'Restaurar backup do Tarkas',properties:['openFile'],filters:[{name:'Backup do Tarkas',extensions:['json']}]});if(choice.canceled||!choice.filePaths[0])return false;importProfile(JSON.parse(fs.readFileSync(choice.filePaths[0],'utf8')));return true});
ipcMain.handle('builds:list',()=>savedBuilds());
ipcMain.handle('builds:save',(_e,name,weaponId,weaponName,notes,items)=>saveBuild(name,weaponId,weaponName,notes,items));
ipcMain.handle('shopping:list',()=>shoppingList());
ipcMain.handle('shopping:add',(_e,name,quantity)=>addShoppingItem(name,quantity));
ipcMain.handle('shopping:complete',(_e,id)=>completeShoppingItem(id));
ipcMain.handle('builds:shopping-missing',(_e,id)=>addBuildMissingToShopping(id));
ipcMain.handle('raids:list',()=>raidHistory());
ipcMain.handle('raids:add',(_e,map,result,summary,loot,kills)=>addRaidLog(map,result,summary,loot,kills));
ipcMain.handle('goals:list',()=>goalsList());
ipcMain.handle('goals:add',(_e,title,kind)=>addGoal(title,kind));
ipcMain.handle('goals:complete',(_e,id)=>completeGoal(id));
ipcMain.handle('pins:list',(_e,map)=>mapPins(map));
ipcMain.handle('pins:add',(_e,map,label,note,x,z)=>addMapPin(map,label,note,x,z));
ipcMain.handle('pins:remove',(_e,id)=>removeMapPin(id));
ipcMain.handle('favorites:list',()=>favorites());
ipcMain.handle('favorites:toggle',(_e,id,name,kind)=>toggleFavorite(id,name,kind));
ipcMain.handle('stash:list',()=>stashItems());
ipcMain.handle('stash:set',(_e,id,name,qty)=>setStashItem(id,name,qty));
ipcMain.handle('reminder:add',(_e,title,dueAt)=>addReminder(title,dueAt));
ipcMain.handle('reminder:complete',(_e,id)=>completeReminder(id));
ipcMain.handle('quest:toggle',(_e,id)=>toggleQuest(id));
ipcMain.handle('setting:save',(_e,key,value)=>{if(key==='playerLevel'){const n=Number(value);if(!Number.isInteger(n)||n<1||n>79)throw new Error('Nível deve estar entre 1 e 79');value=n}return saveSetting(key,value)});
ipcMain.handle('setting:get',(_e,key,fallback)=>getSetting(key,fallback));
ipcMain.handle('player:level',()=>playerLevel());
ipcMain.handle('data:sync',(_e,mode)=>syncCore(mode));
ipcMain.handle('data:status',()=>getStatus());
ipcMain.handle('battlepass:documents',()=>getBattlePassDocuments());
ipcMain.handle('armory:catalog',(_e,mode)=>armoryCatalog(mode));
ipcMain.handle('armory:detail',(_e,mode,id)=>armoryDetails(mode,id));
ipcMain.handle('hideout:catalog',(_e,mode)=>hideoutCatalog(mode));
ipcMain.handle('market:catalog',(_e,mode)=>marketCatalog(mode));
ipcMain.handle('quests:catalog',(_e,mode)=>questSummary(mode));
ipcMain.handle('kappa:tracker',(_e,mode)=>kappaTracker(mode,questProgress()));
ipcMain.handle('progress:get',()=>({quests:questProgress(),objectives:objectiveProgress()}));
ipcMain.handle('progress:quest',(_e,id,status)=>setQuestStatus(id,status));
ipcMain.handle('progress:objective',(_e,id,questId)=>toggleObjective(id,questId));
ipcMain.handle('quests:planned',(_e,mode,level)=>planQuests(mode,questProgress(),level??playerLevel()));
ipcMain.handle('raid:plan',(_e,mode,map,level,focusQuestId)=>raidPlan(mode,map,questProgress(),level??playerLevel(),focusQuestId||''));
ipcMain.handle('maps:list',(_e,mode)=>maps(mode));
ipcMain.handle('maps:detail',(_e,mode,id)=>mapDetail(mode,id));
ipcMain.handle('map:project',(_e,mode,id,position)=>{const m=mapDetail(mode,id);if(!m?.calibration)return null;return{point:projectPoint(position,m.calibration),floor:pointLayer(position,m.calibration)}});
ipcMain.handle('clock:tarkov',()=>tarkovPair());
