(()=>{
  const translations={
    'pt-BR':{languageName:'Português (Brasil)',languageLabel:'Idioma',project:'PROJETO TARKAS',commandCenter:'COMMAND CENTER',loadingVersion:'carregando versão',localData:'Dados locais · quests + mapas + documentos',developedBy:'Desenvolvido por MGOES',dashboard:'Visão Geral',quests:'Quests',mapa:'Mapa Interativo',battlepass:'Battle Pass',hideout:'Hideout',armory:'Arsenal',operations:'Operações',roadmap:'Roadmap',story:'História',market:'Itens e Mercado',search:'Buscar',searchArea:'Buscar área do Tarkas',checkingVersion:'VERIFICANDO VERSÃO',updates:'ATUALIZAÇÕES',checkNow:'Verificar agora',restartInstall:'Instalar e reiniciar',createShortcut:'Criar atalho na área de trabalho'},
    en:{languageName:'English',languageLabel:'Language',project:'TARKAS PROJECT',commandCenter:'COMMAND CENTER',loadingVersion:'loading version',localData:'Local data · quests + maps + documents',developedBy:'Developed by MGOES',dashboard:'Overview',quests:'Quests',mapa:'Interactive Map',battlepass:'Battle Pass',hideout:'Hideout',armory:'Armory',operations:'Operations',roadmap:'Roadmap',story:'Story',market:'Items & Market',search:'Search',searchArea:'Search Tarkas area',checkingVersion:'CHECKING VERSION',updates:'UPDATES',checkNow:'Check now',restartInstall:'Install and restart',createShortcut:'Create desktop shortcut'},
    es:{languageName:'Español',languageLabel:'Idioma',project:'PROYECTO TARKAS',commandCenter:'COMMAND CENTER',loadingVersion:'cargando versión',localData:'Datos locales · misiones + mapas + documentos',developedBy:'Desarrollado por MGOES',dashboard:'Resumen',quests:'Misiones',mapa:'Mapa interactivo',battlepass:'Pase de batalla',hideout:'Guarida',armory:'Arsenal',operations:'Operaciones',roadmap:'Hoja de ruta',story:'Historia',market:'Objetos y mercado',search:'Buscar',searchArea:'Buscar área de Tarkas',checkingVersion:'VERIFICANDO VERSIÓN',updates:'ACTUALIZACIONES',checkNow:'Verificar ahora',restartInstall:'Instalar y reiniciar',createShortcut:'Crear acceso directo en el escritorio'}
  };
  const normalize=value=>String(value||'').toLowerCase().startsWith('pt')?'pt-BR':String(value||'').toLowerCase().startsWith('es')?'es':'en';
  window.tarkasI18n={translations,normalize,detect:()=>normalize(navigator.language),t:(language,key)=>translations[normalize(language)]?.[key]||translations.en[key]||key};
})();
